org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.parallel=true

# AndroidX is the standard for new Android projects.
android.useAndroidX=true
# Generate per-module R classes instead of one merged R class.
android.nonTransitiveRClass=true

kotlin.code.style=official
