package com.agentx.app.integrations.connection

/**
 * Opaque identifier for a saved external-service connection.
 *
 * The value is generated by the [ConnectionManager]; callers must not invent ids
 * or treat them as secrets.
 */
@JvmInline
value class ConnectionId(val value: String) {
    init {
        require(value.isNotBlank()) { "Connection id must not be blank" }
    }

    override fun toString(): String = value
}

/**
 * Kind of external service a connection describes.
 *
 * These are type tags only. Service-specific APIs (GitHub, Supabase, MCP) are
 * implemented in later tasks; this layer never talks to those APIs.
 */
enum class ConnectionType(
    val displayName: String,
    val description: String,
    val defaultCapabilities: Set<ConnectionCapability>,
    val requiresEndpoint: Boolean,
    val defaultAuthMethod: ConnectionAuthMethod,
) {
    GITHUB(
        displayName = "GitHub",
        description = "GitHub repositories, pull requests and issues.",
        defaultCapabilities = ConnectionCapabilities.GITHUB,
        requiresEndpoint = false,
        defaultAuthMethod = ConnectionAuthMethod.ACCESS_TOKEN,
    ),
    SUPABASE(
        displayName = "Supabase",
        description = "Supabase projects, database, storage and metadata.",
        defaultCapabilities = ConnectionCapabilities.SUPABASE,
        requiresEndpoint = true,
        defaultAuthMethod = ConnectionAuthMethod.API_KEY,
    ),
    MCP_SERVER(
        displayName = "MCP server",
        description = "A Model Context Protocol server exposing tools, resources or prompts.",
        defaultCapabilities = ConnectionCapabilities.MCP,
        requiresEndpoint = false,
        defaultAuthMethod = ConnectionAuthMethod.NONE,
    ),
    CUSTOM_API(
        displayName = "Custom API",
        description = "A generic HTTP API described by the user.",
        defaultCapabilities = ConnectionCapabilities.CUSTOM,
        requiresEndpoint = true,
        defaultAuthMethod = ConnectionAuthMethod.API_KEY,
    ),
}

/**
 * Lifecycle of a saved connection. A type that has no tester must never report
 * [CONNECTED]; it stays [NOT_CONFIGURED] or [DISCONNECTED] until a real tester
 * exists.
 */
enum class ConnectionStatus(val displayName: String) {
    NOT_CONFIGURED("Not configured"),
    DISCONNECTED("Disconnected"),
    CONNECTING("Connecting"),
    CONNECTED("Connected"),
    ERROR("Error"),
}

/**
 * How the user authenticates with the external service. This is a data contract
 * for the form and the secret store; OAuth is represented but not performed.
 */
enum class ConnectionAuthMethod(val displayName: String, val requiresSecret: Boolean) {
    OAUTH("OAuth", requiresSecret = false),
    API_KEY("API key", requiresSecret = true),
    ACCESS_TOKEN("Access token", requiresSecret = true),
    USERNAME_PASSWORD("Username and password", requiresSecret = true),
    NONE("None", requiresSecret = false),
}

/**
 * A named capability a connection may declare. Tools later request a
 * [ConnectionType] plus one of these; they never receive credentials.
 */
@JvmInline
value class ConnectionCapability(val id: String) {
    init {
        require(id.isNotBlank()) { "Capability id must not be blank" }
        require(id.matches(ID_PATTERN)) {
            "Capability id '$id' must contain only lowercase letters, digits or '_'"
        }
    }

    override fun toString(): String = id

    companion object {
        val ID_PATTERN = Regex("[a-z0-9_]+")

        fun of(id: String): ConnectionCapability = ConnectionCapability(id)
    }
}

/** Built-in capability ids. Definitions only — no service calls happen here. */
object ConnectionCapabilities {
    val REPOSITORY_READ = ConnectionCapability("repository_read")
    val REPOSITORY_WRITE = ConnectionCapability("repository_write")
    val PULL_REQUEST = ConnectionCapability("pull_request")
    val ISSUES = ConnectionCapability("issues")

    val DATABASE_READ = ConnectionCapability("database_read")
    val DATABASE_WRITE = ConnectionCapability("database_write")
    val STORAGE = ConnectionCapability("storage")
    val PROJECT_METADATA = ConnectionCapability("project_metadata")

    val TOOLS = ConnectionCapability("tools")
    val RESOURCES = ConnectionCapability("resources")
    val PROMPTS = ConnectionCapability("prompts")

    val HTTP_REQUEST = ConnectionCapability("http_request")

    val GITHUB: Set<ConnectionCapability> = setOf(
        REPOSITORY_READ,
        REPOSITORY_WRITE,
        PULL_REQUEST,
        ISSUES,
    )

    val SUPABASE: Set<ConnectionCapability> = setOf(
        DATABASE_READ,
        DATABASE_WRITE,
        STORAGE,
        PROJECT_METADATA,
    )

    val MCP: Set<ConnectionCapability> = setOf(TOOLS, RESOURCES, PROMPTS)

    val CUSTOM: Set<ConnectionCapability> = setOf(HTTP_REQUEST)

    fun defaultsFor(type: ConnectionType): Set<ConnectionCapability> = type.defaultCapabilities
}

/**
 * Non-secret configuration for a connection. Endpoints and usernames live here;
 * passwords, tokens and API keys never do.
 */
data class ConnectionConfig(
    val endpoint: String? = null,
    val authMethod: ConnectionAuthMethod = ConnectionAuthMethod.NONE,
    val username: String? = null,
    val metadata: Map<String, String> = emptyMap(),
) {
    /** True when a credential is expected to exist in the secret store. */
    val expectsCredential: Boolean get() = authMethod.requiresSecret
}

/**
 * Handle for a stored credential. The secret itself is never carried on a
 * [Connection]; tools receive this reference only after authorization.
 */
data class ConnectionCredential(
    val ref: String,
    val present: Boolean,
) {
    override fun toString(): String = "ConnectionCredential(present=$present)"
}

/**
 * A saved, reproducible description of one external service.
 *
 * Credentials are referenced, never stored. [toString] is safe to log: it does
 * not include secrets because none exist on this type.
 */
data class Connection(
    val id: ConnectionId,
    val displayName: String,
    val type: ConnectionType,
    val config: ConnectionConfig = ConnectionConfig(),
    val capabilities: Set<ConnectionCapability> = ConnectionCapabilities.defaultsFor(type),
    val enabled: Boolean = true,
    val status: ConnectionStatus = ConnectionStatus.NOT_CONFIGURED,
    val statusMessage: String? = null,
    val lastTestedAtMillis: Long? = null,
    val credentialRef: String? = null,
    val createdAtMillis: Long = 0L,
    val updatedAtMillis: Long = 0L,
) {
    val hasCredential: Boolean get() = !credentialRef.isNullOrBlank()

    val isConfigured: Boolean get() = validate().isEmpty()

    /**
     * Returns every configuration problem found; an empty list means the
     * connection can be saved. Messages are user-facing and contain no secrets.
     */
    fun validate(): List<String> {
        val errors = mutableListOf<String>()
        if (displayName.isBlank()) errors += "Name must not be blank"
        if (type.requiresEndpoint && config.endpoint.isNullOrBlank()) {
            errors += "An endpoint or base URL is required for ${type.displayName}"
        }
        config.endpoint?.takeIf { it.isNotBlank() }?.let { url ->
            if (!looksLikeUrl(url)) errors += "Endpoint must be a valid URL"
        }
        if (config.authMethod == ConnectionAuthMethod.USERNAME_PASSWORD && config.username.isNullOrBlank()) {
            errors += "A username is required for username/password authentication"
        }
        capabilities.forEach { capability ->
            if (capability.id.isBlank()) errors += "Capability ids must not be blank"
        }
        return errors
    }

    /** Non-secret snapshot a tool may inspect after authorization. */
    fun authorizedHandle(): AuthorizedConnection =
        AuthorizedConnection(
            id = id,
            displayName = displayName,
            type = type,
            capabilities = capabilities,
            endpoint = config.endpoint,
            authMethod = config.authMethod,
            credentialRef = credentialRef,
        )

    companion object {
        private val URL_PATTERN = Regex("(?i)^https?://\\S+$")

        fun looksLikeUrl(raw: String): Boolean = URL_PATTERN.matches(raw.trim())
    }
}

/**
 * What an authorized tool is allowed to see: identity, type, capabilities and
 * a credential *reference*. The secret is never on this object.
 */
data class AuthorizedConnection(
    val id: ConnectionId,
    val displayName: String,
    val type: ConnectionType,
    val capabilities: Set<ConnectionCapability>,
    val endpoint: String? = null,
    val authMethod: ConnectionAuthMethod = ConnectionAuthMethod.NONE,
    val credentialRef: String? = null,
) {
    override fun toString(): String =
        "AuthorizedConnection(id=$id, type=${type.name}, capabilities=${capabilities.map { it.id }})"
}

/**
 * Draft used to create or update a connection. [credential] is write-only: it
 * is handed to the secret store and never persisted on the [Connection].
 */
data class ConnectionDraft(
    val id: ConnectionId? = null,
    val displayName: String,
    val type: ConnectionType,
    val config: ConnectionConfig = ConnectionConfig(authMethod = type.defaultAuthMethod),
    val capabilities: Set<ConnectionCapability> = ConnectionCapabilities.defaultsFor(type),
    val enabled: Boolean = true,
    val credential: String? = null,
    val clearCredential: Boolean = false,
) {
    fun toConnection(
        id: ConnectionId,
        existing: Connection?,
        credentialRef: String?,
        now: Long,
        status: ConnectionStatus = existing?.status ?: ConnectionStatus.NOT_CONFIGURED,
        statusMessage: String? = existing?.statusMessage,
        lastTestedAtMillis: Long? = existing?.lastTestedAtMillis,
    ): Connection = Connection(
        id = id,
        displayName = displayName.trim(),
        type = type,
        config = config.copy(
            endpoint = config.endpoint?.trim()?.takeIf { it.isNotBlank() },
            username = config.username?.trim()?.takeIf { it.isNotBlank() },
        ),
        capabilities = capabilities.ifEmpty { ConnectionCapabilities.defaultsFor(type) },
        enabled = enabled,
        status = if (existing != null && existing.type == type) status else ConnectionStatus.NOT_CONFIGURED,
        statusMessage = if (existing != null && existing.type == type) statusMessage else null,
        lastTestedAtMillis = if (existing != null && existing.type == type) lastTestedAtMillis else null,
        credentialRef = credentialRef,
        createdAtMillis = existing?.createdAtMillis ?: now,
        updatedAtMillis = now,
    )
}

/** Result of probing a connection. Never reports connected for unsupported types. */
data class ConnectionTestResult(
    val status: ConnectionStatus,
    val message: String,
    val testedAtMillis: Long,
) {
    val succeeded: Boolean get() = status == ConnectionStatus.CONNECTED

    companion object {
        const val NOT_IMPLEMENTED: String = "Connection test is not implemented yet."

        fun unsupported(now: Long): ConnectionTestResult = ConnectionTestResult(
            status = ConnectionStatus.DISCONNECTED,
            message = NOT_IMPLEMENTED,
            testedAtMillis = now,
        )
    }
}

/** Why a tool was refused a connection. Safe to surface to the agent. */
enum class ConnectionAuthorizationFailure(val message: String) {
    NOT_FOUND("No connection matches the requested type"),
    DISABLED("The matching connection is disabled"),
    MISSING_CAPABILITY("The connection does not declare the required capability"),
    MISSING_CREDENTIAL("The connection has no stored credential"),
    NOT_AUTHORIZED("The connection is not authorized for this tool"),
}

/**
 * Structured refusal returned when a tool cannot be given a connection.
 * Contains no secrets.
 */
data class ConnectionAuthorizationError(
    val failure: ConnectionAuthorizationFailure,
    val type: ConnectionType,
    val capability: ConnectionCapability,
    val connectionId: ConnectionId? = null,
    val detail: String? = null,
) {
    val message: String get() = detail ?: failure.message

    override fun toString(): String =
        "ConnectionAuthorizationError(failure=${failure.name}, type=${type.name}, capability=${capability.id})"
}
