package com.agentx.app.integrations.connection

/**
 * Opaque identifier for a saved external-service connection.
 *
 * The value is generated by the [ConnectionManager]; callers must not invent ids
 * or treat them as secrets.
 */
@JvmInline
value class ConnectionId(val value: String) {
    init {
        require(value.isNotBlank()) { "Connection id must not be blank" }
    }

    override fun toString(): String = value
}

/**
 * Kind of external service a connection describes.
 *
 * These are type tags only. Service-specific APIs (GitHub, Supabase, MCP) are
 * implemented in later tasks; this layer never talks to those APIs.
 *
 * [oauthSupported] is true when an official OAuth provider exists for the type.
 * OAuth is then the preferred method and [defaultAuthMethod] is
 * [ConnectionAuthMethod.OAUTH]; manual credentials stay available as a fallback.
 */
enum class ConnectionType(
    val displayName: String,
    val description: String,
    val defaultCapabilities: Set<ConnectionCapability>,
    val requiresEndpoint: Boolean,
    val defaultAuthMethod: ConnectionAuthMethod,
    val oauthSupported: Boolean = false,
) {
    GITHUB(
        displayName = "GitHub",
        description = "GitHub repositories, pull requests and issues.",
        defaultCapabilities = ConnectionCapabilities.GITHUB,
        requiresEndpoint = false,
        defaultAuthMethod = ConnectionAuthMethod.OAUTH,
        oauthSupported = true,
    ),
    SUPABASE(
        displayName = "Supabase",
        description = "Supabase projects, database, storage and metadata.",
        defaultCapabilities = ConnectionCapabilities.SUPABASE,
        requiresEndpoint = true,
        defaultAuthMethod = ConnectionAuthMethod.OAUTH,
        oauthSupported = true,
    ),
    MCP_SERVER(
        displayName = "MCP server",
        description = "A Model Context Protocol server exposing tools, resources or prompts.",
        defaultCapabilities = ConnectionCapabilities.MCP,
        requiresEndpoint = false,
        defaultAuthMethod = ConnectionAuthMethod.NONE,
    ),
    CUSTOM_API(
        displayName = "Custom API",
        description = "A generic HTTP API described by the user.",
        defaultCapabilities = ConnectionCapabilities.CUSTOM,
        requiresEndpoint = true,
        defaultAuthMethod = ConnectionAuthMethod.API_KEY,
    ),
}

/**
 * Lifecycle of a saved connection.
 *
 * OAuth connections move `NOT_CONNECTED → AUTHORIZING → CONNECTED`, and fall to
 * [EXPIRED] when their credentials stop working. A type that has no tester, or a
 * connection whose authorization never completed, must never report [CONNECTED].
 */
enum class ConnectionStatus(val displayName: String) {
    NOT_CONNECTED("Not connected"),
    AUTHORIZING("Waiting for authorization"),
    VERIFYING("Verifying"),
    CONNECTING("Connecting"),
    CONNECTED("Connected"),
    EXPIRED("Connection expired"),
    DISCONNECTED("Disconnected"),
    ERROR("Connection error"),
    ;

    /** True when the connection has usable credentials. */
    val isConnected: Boolean get() = this == CONNECTED

    /** True while the provider's authorization page is open or being handled. */
    val isAuthorizing: Boolean get() = this == AUTHORIZING

    /** True while the app is working on the connection (authorizing, verifying, probing). */
    val isBusy: Boolean get() = this == AUTHORIZING || this == VERIFYING || this == CONNECTING

    /** True when the user has to act again: reconnect, re-authorize or fix a setting. */
    val needsUserAction: Boolean get() = this == EXPIRED || this == ERROR || this == NOT_CONNECTED
}

/**
 * How the user authenticates with the external service.
 *
 * [OAUTH] is the preferred method for every service that supports it: the user
 * approves access on the provider's own page and the app stores the resulting
 * tokens. [API_KEY] and [ACCESS_TOKEN] remain available as manual fallbacks for
 * services without OAuth, and [NONE] for open services.
 */
enum class ConnectionAuthMethod(val displayName: String, val requiresSecret: Boolean) {
    OAUTH("OAuth", requiresSecret = false),
    API_KEY("API key", requiresSecret = true),
    ACCESS_TOKEN("Access token", requiresSecret = true),
    USERNAME_PASSWORD("Username and password", requiresSecret = true),
    NONE("None", requiresSecret = false),
    ;

    /** True for the manual credential methods, which are a fallback only. */
    val isManualCredential: Boolean
        get() = this == API_KEY || this == ACCESS_TOKEN || this == USERNAME_PASSWORD
}

/**
 * A named capability a connection may declare. Tools later request a
 * [ConnectionType] plus one of these; they never receive credentials.
 */
@JvmInline
value class ConnectionCapability(val id: String) {
    init {
        require(id.isNotBlank()) { "Capability id must not be blank" }
        require(id.matches(ID_PATTERN)) {
            "Capability id '$id' must contain only lowercase letters, digits or '_'"
        }
    }

    override fun toString(): String = id

    companion object {
        val ID_PATTERN = Regex("[a-z0-9_]+")

        fun of(id: String): ConnectionCapability = ConnectionCapability(id)
    }
}

/** Built-in capability ids. Definitions only — no service calls happen here. */
object ConnectionCapabilities {
    val REPOSITORY_READ = ConnectionCapability("repository_read")
    val REPOSITORY_WRITE = ConnectionCapability("repository_write")
    val PULL_REQUEST = ConnectionCapability("pull_request")
    val ISSUES = ConnectionCapability("issues")

    val DATABASE_READ = ConnectionCapability("database_read")
    val DATABASE_WRITE = ConnectionCapability("database_write")
    val STORAGE = ConnectionCapability("storage")
    val PROJECT_METADATA = ConnectionCapability("project_metadata")

    val TOOLS = ConnectionCapability("tools")
    val RESOURCES = ConnectionCapability("resources")
    val PROMPTS = ConnectionCapability("prompts")

    val HTTP_REQUEST = ConnectionCapability("http_request")

    val GITHUB: Set<ConnectionCapability> = setOf(
        REPOSITORY_READ,
        REPOSITORY_WRITE,
        PULL_REQUEST,
        ISSUES,
    )

    val SUPABASE: Set<ConnectionCapability> = setOf(
        DATABASE_READ,
        DATABASE_WRITE,
        STORAGE,
        PROJECT_METADATA,
    )

    val MCP: Set<ConnectionCapability> = setOf(TOOLS, RESOURCES, PROMPTS)

    val CUSTOM: Set<ConnectionCapability> = setOf(HTTP_REQUEST)

    fun defaultsFor(type: ConnectionType): Set<ConnectionCapability> = type.defaultCapabilities
}

/**
 * Non-secret configuration for a connection. Endpoints and usernames live here;
 * passwords, tokens and API keys never do.
 */
data class ConnectionConfig(
    val endpoint: String? = null,
    val authMethod: ConnectionAuthMethod = ConnectionAuthMethod.NONE,
    val username: String? = null,
    val metadata: Map<String, String> = emptyMap(),
) {
    /** True when a credential is expected to exist in the secret store. */
    val expectsCredential: Boolean get() = authMethod.requiresSecret
}

/**
 * Handle for a stored credential. The secret itself is never carried on a
 * [Connection]; tools receive this reference only after authorization.
 */
data class ConnectionCredential(
    val ref: String,
    val present: Boolean,
) {
    override fun toString(): String = "ConnectionCredential(present=$present)"
}

/**
 * A saved, reproducible description of one external service.
 *
 * Credentials are referenced, never stored. [toString] is safe to log: it does
 * not include secrets because none exist on this type.
 */
data class Connection(
    val id: ConnectionId,
    val displayName: String,
    val type: ConnectionType,
    val config: ConnectionConfig = ConnectionConfig(),
    val capabilities: Set<ConnectionCapability> = ConnectionCapabilities.defaultsFor(type),
    val enabled: Boolean = true,
    val status: ConnectionStatus = ConnectionStatus.NOT_CONNECTED,
    val statusMessage: String? = null,
    val lastTestedAtMillis: Long? = null,
    val credentialRef: String? = null,
    /**
     * Scopes the provider actually granted. Capabilities are derived from this
     * set, so a connection never claims access the authorization did not give it.
     */
    val grantedScopes: Set<String> = emptySet(),
    /** Non-secret label of the authorized account, when the provider reports one. */
    val accountLabel: String? = null,
    /** When the stored credentials stop working, when the provider reports it. */
    val credentialsExpireAtMillis: Long? = null,
    /** True when the provider issued a refresh token for this connection. */
    val refreshable: Boolean = false,
    val createdAtMillis: Long = 0L,
    val updatedAtMillis: Long = 0L,
) {
    val hasCredential: Boolean get() = !credentialRef.isNullOrBlank()

    val isConfigured: Boolean get() = validate().isEmpty()

    /** True when this connection is authorized through OAuth. */
    val usesOAuth: Boolean get() = config.authMethod == ConnectionAuthMethod.OAUTH

    /** True when the connection is authorized and its credentials are usable. */
    val isConnected: Boolean get() = status == ConnectionStatus.CONNECTED && hasCredential

    /**
     * Returns every configuration problem found; an empty list means the
     * connection can be saved. Messages are user-facing and contain no secrets.
     */
    fun validate(): List<String> {
        val errors = mutableListOf<String>()
        if (displayName.isBlank()) errors += "Name must not be blank"
        // OAuth connections reach the provider's own API, so no user-supplied
        // endpoint is needed; the manual methods still require one when the
        // service has no fixed base URL.
        if (type.requiresEndpoint && !usesOAuth && config.endpoint.isNullOrBlank()) {
            errors += "An endpoint or base URL is required for ${type.displayName}"
        }
        config.endpoint?.takeIf { it.isNotBlank() }?.let { url ->
            if (!looksLikeUrl(url)) errors += "Endpoint must be a valid URL"
        }
        if (config.authMethod == ConnectionAuthMethod.USERNAME_PASSWORD && config.username.isNullOrBlank()) {
            errors += "A username is required for username/password authentication"
        }
        capabilities.forEach { capability ->
            if (capability.id.isBlank()) errors += "Capability ids must not be blank"
        }
        return errors
    }

    /** Non-secret snapshot a tool may inspect after authorization. */
    fun authorizedHandle(): AuthorizedConnection =
        AuthorizedConnection(
            id = id,
            displayName = displayName,
            type = type,
            capabilities = capabilities,
            endpoint = config.endpoint,
            authMethod = config.authMethod,
            credentialRef = credentialRef,
            status = status,
            accountLabel = accountLabel,
        )

    companion object {
        private val URL_PATTERN = Regex("(?i)^https?://\\S+$")

        fun looksLikeUrl(raw: String): Boolean = URL_PATTERN.matches(raw.trim())
    }
}

/**
 * What an authorized tool is allowed to see: identity, type, capabilities and
 * a credential *reference*. The secret is never on this object.
 */
data class AuthorizedConnection(
    val id: ConnectionId,
    val displayName: String,
    val type: ConnectionType,
    val capabilities: Set<ConnectionCapability>,
    val endpoint: String? = null,
    val authMethod: ConnectionAuthMethod = ConnectionAuthMethod.NONE,
    val credentialRef: String? = null,
    val status: ConnectionStatus = ConnectionStatus.NOT_CONNECTED,
    /** Non-secret account label. Never a token. */
    val accountLabel: String? = null,
) {
    override fun toString(): String =
        "AuthorizedConnection(id=$id, type=${type.name}, capabilities=${capabilities.map { it.id }})"
}

/**
 * Draft used to create or update a connection. [credential] is write-only: it
 * is handed to the secret store and never persisted on the [Connection].
 */
data class ConnectionDraft(
    val id: ConnectionId? = null,
    val displayName: String,
    val type: ConnectionType,
    val config: ConnectionConfig = ConnectionConfig(authMethod = type.defaultAuthMethod),
    val capabilities: Set<ConnectionCapability> = ConnectionCapabilities.defaultsFor(type),
    val enabled: Boolean = true,
    val credential: String? = null,
    val clearCredential: Boolean = false,
) {
    fun toConnection(
        id: ConnectionId,
        existing: Connection?,
        credentialRef: String?,
        now: Long,
        status: ConnectionStatus = existing?.status ?: ConnectionStatus.NOT_CONNECTED,
        statusMessage: String? = existing?.statusMessage,
        lastTestedAtMillis: Long? = existing?.lastTestedAtMillis,
    ): Connection {
        val sameType = existing != null && existing.type == type
        val keepsGrant = sameType && config.authMethod == ConnectionAuthMethod.OAUTH
        return Connection(
            id = id,
            displayName = displayName.trim(),
            type = type,
            config = config.copy(
                endpoint = config.endpoint?.trim()?.takeIf { it.isNotBlank() },
                username = config.username?.trim()?.takeIf { it.isNotBlank() },
            ),
            capabilities = capabilities.ifEmpty { ConnectionCapabilities.defaultsFor(type) },
            enabled = enabled,
            status = if (sameType) status else ConnectionStatus.NOT_CONNECTED,
            statusMessage = if (sameType) statusMessage else null,
            lastTestedAtMillis = if (sameType) lastTestedAtMillis else null,
            credentialRef = credentialRef,
            // Switching a connection to a manual method drops the OAuth grant:
            // stale scopes must never describe the new credentials.
            grantedScopes = if (keepsGrant) existing.grantedScopes else emptySet(),
            accountLabel = if (keepsGrant) existing.accountLabel else null,
            credentialsExpireAtMillis = if (keepsGrant) existing.credentialsExpireAtMillis else null,
            refreshable = keepsGrant && existing.refreshable,
            createdAtMillis = existing?.createdAtMillis ?: now,
            updatedAtMillis = now,
        )
    }
}

/** Result of probing a connection. Never reports connected for unsupported types. */
data class ConnectionTestResult(
    val status: ConnectionStatus,
    val message: String,
    val testedAtMillis: Long,
) {
    val succeeded: Boolean get() = status == ConnectionStatus.CONNECTED

    companion object {
        const val NOT_IMPLEMENTED: String = "Connection test is not implemented yet."

        fun unsupported(now: Long): ConnectionTestResult = ConnectionTestResult(
            status = ConnectionStatus.DISCONNECTED,
            message = NOT_IMPLEMENTED,
            testedAtMillis = now,
        )
    }
}
